export const SIGNUP_USER_STARTED = "SIGNUP_USER_STARTED";
export const SIGNUP_USER_SUCCEEDED = "SIGNUP_USER_SUCCEDED";
export const SIGNUP_USER_FAILED = "SIGNUP_USER_FAILED";

export const VERIFY_USER_ACCOUNT_STARTED = "VERIFY_USER_ACCOUNT_STARTED";
export const VERIFY_USER_ACCOUNT_SUCCEDED = "VERIFY_USER_ACCOUNT_SUCCEDED";
export const VERIFY_USER_ACCOUNT_FAIL = "VERIFY_USER_ACCOUNT_FAIL";
