export const SIGNUP_USER_STARTED = "SIGNUP_USER_STARTED";
export const SIGNUP_USER_SUCCEEDED = "SIGNUP_USER_SUCCEDED";
export const SIGNUP_USER_FAILED = "SIGNUP_USER_FAILED";

export const VERIFY_USER_ACCOUNT_STARTED = "VERIFY_USER_ACCOUNT_STARTED";
export const VERIFY_USER_ACCOUNT_SUCCEDED = "VERIFY_USER_ACCOUNT_SUCCEDED";
export const VERIFY_USER_ACCOUNT_FAIL = "VERIFY_USER_ACCOUNT_FAIL";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const DELETE_ARTICLE_FAIL = "DELETE_ARTICLE_FAIL";

export const GET_ARTICLE_START = "GET_ARTICLE_START";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAIL = "GET_ARTICLE_FAIL";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_FAIL = "CREATE_ARTICLE_FAIL";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAIL = "UPDATE_ARTICLE_FAIL";

export const ACTION_ENDED = "ACTION_ENDED";

export const FETCH_COMMENTS_ACTION = "FETCH_COMMENTS_ACTION";
export const FETCH_REPLIES_ACTION = "FETCH_REPLIES_ACTION";
export const CREATE_COMMENT_ACTION = "CREATE_COMMENT_ACTION";
export const UPDATE_COMMENT_ACTION = "UPDATE_COMMENT_ACTION";
export const DELETE_COMMENT_ACTION = "DELETE_COMMENT_ACTION";
export const CREATE_REPLY_ACTION = "CREATE_REPLY_ACTION";
export const UPDATE_REPLY_ACTION = "UPDATE_REPLY_ACTION";
export const DELETE_REPLY_ACTION = "DELETE_REPLY_ACTION";
export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const STARTED_FETCH_USER_PROFILE = "STARTED_FETCH_USER_PROFILE";
export const STARTED_REQUEST_EDIT_PROFILE = "STARTED_REQUEST_EDIT_PROFILE";
export const DISMISS_MESSAGE = "DISMISS_MESSAGE";
export const REQUEST_EDIT_FAILURE = "REQUEST_EDIT_FAILURE";
export const FAILED_FETCH_PROFILE = "FAILED_FETCH_PROFILE";
export const FAILED_UPDATE_PROFILE = "FAILED_UPDATE_PROFILE";
export const STARTED_FETCH_FOLLOWERS = "STARTED_FETCH_FOLLOWERS";
export const STARTED_FETCH_FOLLOWING = "STARTED_FETCH_FOLLOWING";
export const FETCH_TAGS_ACTION = "FETCH_TAGS_ACTION";
export const FETCH_TAG_FILTER_ACTION = "FETCH_TAG_FILTER_ACTION";
